### PR TITLE
Add hplip and enable remote printing

### LINKED ISSUE #1: Unable to print from client on same subnet
Unable to print from a shared printer on the network unless I also enable "Allow printing from the internet" in server settings: 
image

**Expected behavior:**
When sharing a printer, clients on the same network should be able to print to that printer. 

**Actual behavior**:
The client is able to discover printer but when trying to print, presented with _"You do not have permission to use this printer"_. Must enable Allow printing from the internet" in server settings for it to work.

### PR DESCRIPTION
**Pull request by rahul-thakoor**
- Enable printer sharing and allow printing from internet in Server settings by default
- Add a startup message
- Add `hplip` package which provides support for numerous popular hp printers

closes #1

### CODE REVIEW

**Review by willswire — CHANGES_REQUESTED** [review]
Looking at the changes in `cups.conf` -- what is the advantage of `Listen 80` vs `Port 80`? Just wanting clarification, as I know these changes have created issues when trying to AirPrint from an iOS device. Can you confirm printing from an iOS device is still possible with this change?

**Comment by rahul-thakoor** [comment]
According to the documentation :

> The Listen directive is similar to the Port directive but allows you to restrict access to specific interfaces or networks

Let me change it back actually. I think using different directives together can cause issues.

**Review by willswire — APPROVED** [review]

**Comment by rahul-thakoor** [comment]
I can confirm it works with iOS, macOS, Android and Windows

**Comment by rahul-thakoor** [comment]
@willswire would you happen to know if the order of the Listen directives matter?

using 
```
Listen 80
Listen 631
```
on Android in detects the printer but cannot get it's information or send print job while swapping to 

```
Listen 631
Listen 80
````
works immediately. I'm not sure if this is related to my device or the case for all

**Comment by willswire** [comment]
@rahul-thakoor not sure, although I would say let's just go with the second ordering as it works.  Also, I am getting a merge conflict for the Dockerfile - could you reformat and commit that file so I can merge this PR online?

**Comment by rahul-thakoor** [comment]
I'm keeping the original ordering since it breaks other platforms.

Let's see if others experience this issue with Android devices then we can tackle it. Thanks a lot Will

**Comment by willswire** [comment]
Thank you for the changes!

**Pull request merged**
